### ISSUE TITLE
make a nice gui

### ISSUE THREAD

**Issue by steen-e** [krismaz/BrewLinker#16]
Nice gui .
two buttons with pump on / off. reed green indicator
arrow up down. temp. celsius - + on the fly (or when paused)
arrow up down time change on the fly - + (or when paused)
 pause button . pause / start. "stop the time, stop heating"   continue time continue heating.
large elapsed time display
large left time display
large temperature display.
perhaps some display of the steps in the proces

**Comment by krismaz** [comment]
Jeg har fundet en løsning, det bliver QT5
